// Auto-generated by tooling/vite/json-locale-types. DO NOT EDIT.
// Source: packages/admin/src/locales

export interface AdminLoginPage {
  en: {
    loading: {
      title: string;
      description: string;
    };
    alreadySignedIn: {
      title: string;
      signedInAs: string;
      generic: string;
    };
    status: {
      expired: string;
      forbidden: string;
      signedOut: string;
      unknown: string;
    };
    form: {
      signIn: string;
      username: string;
      password: string;
      rememberMe: string;
      signingIn: string;
    };
  };
  "zh-CN": {
    loading: {
      title: string;
      description: string;
    };
    alreadySignedIn: {
      title: string;
      signedInAs: string;
      generic: string;
    };
    status: {
      expired: string;
      forbidden: string;
      signedOut: string;
      unknown: string;
    };
    form: {
      signIn: string;
      username: string;
      password: string;
      rememberMe: string;
      signingIn: string;
    };
  };
}

export interface AdminShell {
  en: {
    account: {
      signOut: string;
    };
    fontSize: {
      small: string;
      medium: string;
      large: string;
    };
    aria: {
      fontSize: string;
      language: string;
      account: string;
      theme: string;
      sidebarExpand: string;
      sidebarCollapse: string;
    };
    tabs: {
      openPages: string;
    };
    errors: {
      unableToNavigate: string;
      unableToCloseTab: string;
    };
    signedIn: string;
  };
  "zh-CN": {
    account: {
      signOut: string;
    };
    fontSize: {
      small: string;
      medium: string;
      large: string;
    };
    aria: {
      fontSize: string;
      language: string;
      account: string;
      theme: string;
      sidebarExpand: string;
      sidebarCollapse: string;
    };
    tabs: {
      openPages: string;
    };
    errors: {
      unableToNavigate: string;
      unableToCloseTab: string;
    };
    signedIn: string;
  };
}

export interface HMRTest {
  en: {
    title: string;
    status: string;
  };
  "zh-CN": {
    title: string;
    status: string;
  };
}

/** Maps each locale file's relative stem to its generated message type. */
export interface LocaleFileMap {
  "AdminLoginPage": AdminLoginPage;
  "AdminShell": AdminShell;
  "HMRTest": HMRTest;
}
