// Auto-generated by tooling/vite/json-locale-types. DO NOT EDIT.
// Source: packages/ui/src/locales

export interface Example {
  en: {
    title: string;
    description: string;
  };
  "zh-CN": {
    title: string;
    description: string;
  };
}

/** Maps each locale file's relative stem to its generated message type. */
export interface LocaleFileMap {
  "Example": Example;
}
