/// <reference types="vite/client" />

/** Generated by @noob/tooling-vite hmrPatchServer — do not edit. */
declare module "virtual:noob-hmr-patch" {
  const client: {
    applyUiSource(): Promise<void>;
    restoreUiSource(): Promise<void>;
    applyUiLocale(): Promise<void>;
    restoreUiLocale(): Promise<void>;
    applyAdminSource(): Promise<void>;
    restoreAdminSource(): Promise<void>;
    applyAdminLocale(): Promise<void>;
    restoreAdminLocale(): Promise<void>;
    applyDemoSource(): Promise<void>;
    restoreDemoSource(): Promise<void>;
    applyDemoLocale(): Promise<void>;
    restoreDemoLocale(): Promise<void>;
  };
  export default client;
}
