
/// <reference types="vite/client" />

/**
 * Generated by @noob/tooling-vite hmrPatchServer — do not edit.
 */
declare module "virtual:noob-hmr-patch" {
  import { useHmrPatchClient } from "@noob/tooling-vite/client";
  export type PatchId = 
      | "uiSource"
      | "uiLocale"
      | "adminSource"
      | "adminLocale"
      | "demoSource"
      | "demoLocale";

  export const client: ReturnType<typeof useHmrPatchClient<PatchId>>;
}
